micronaut:
  application:
    name: project-greenthumb
  server:
    port: 81
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:public
datasources:
  default:
    ocid:
    username:
    password:
    driverClassName: oracle.jdbc.OracleDriver
    dialect: ORACLE
    wallet-password: 
mqtt:
  client:
    userName:
    password:
    serverUri:
    clientId:
    connectionTimeout: 30s
    automaticReconnect: true
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
oci:
  config:
    profile: recursivecodes
codes:
  recursive:
    pushover:
      userKey: ${CODES_RECURSIVE_PUSHOVER_USER_KEY}
      apiKey: ${CODES_RECURSIVE_PUSHOVER_API_KEY}