name: Build & Deploy Project GreenThumb
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:  
        java-version: '11.0.3'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew assemble
      
    - name: 'Login To OCIR'
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.OCIR_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.OCIR_PASSWORD }}
        DOCKER_REGISTRY_URL: iad.ocir.io
      
    - name: 'Docker Build'
      uses: docker/setup-buildx-action@v2
      with:
        tags: iad.ocir.io/idatzojkinhi/greenthumb/greenthumb-client:latest
        push: true
        platforms: linux/arm64

    - name: 'Deploy Container'
      uses: appleboy/ssh-action@master
      with:
        host: greenthumb.toddrsharp.com
        username: opc
        key: ${{ secrets.VM_PRIV_KEY }}
        script: |
          echo "${{ secrets.OCIR_PASSWORD }}" | docker login iad.ocir.io --username idatzojkinhi/registry --password-stdin
          docker stop project-greenthumb
          docker rm project-greenthumb
          docker pull iad.ocir.io/idatzojkinhi/greenthumb/greenthumb-client:latest
          docker run -d --name project-greenthumb --restart=always --env MICRONAUT_ENVIRONMENTS=oraclecloud --env CODES_RECURSIVE_PUSHOVER_USER_KEY=${{secrets.CODES_RECURSIVE_PUSHOVER_USER_KEY}} --env CODES_RECURSIVE_PUSHOVER_API_KEY=${{secrets.CODES_RECURSIVE_PUSHOVER_API_KEY}} --env MQTT_CLIENT_USER_NAME=${{ secrets.MQTT_CLIENT_USER_NAME }} --env DATASOURCES_DEFAULT_USERNAME=${{ secrets.DATASOURCES_DEFAULT_USERNAME }} --env MQTT_CLIENT_PASSWORD=${{ secrets.MQTT_CLIENT_PASSWORD }} --env DATASOURCES_DEFAULT_OCID=${{ secrets.DATASOURCES_DEFAULT_OCID }} --env MQTT_CLIENT_CLIENT_ID=${{ secrets.MQTT_CLIENT_CLIENT_ID }} --env DATASOURCES_DEFAULT_PASSWORD=${{ secrets.DATASOURCES_DEFAULT_PASSWORD }} --env MQTT_CLIENT_SERVER_URI=${{ secrets.MQTT_CLIENT_SERVER_URI }} --env DATASOURCES_DEFAULT_WALLET_PASSWORD=${{ secrets.DATASOURCES_DEFAULT_WALLET_PASSWORD }} -p 81:80 iad.ocir.io/idatzojkinhi/greenthumb/greenthumb-client:latest
