# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:  
        java-version: '11.0.3'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew assemble
      
    - name: 'Login To OCIR'
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.OCIR_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.OCIR_PASSWORD }}
        DOCKER_REGISTRY_URL: phx.ocir.io
      
    - name: 'Docker Build'
      run: docker build -t phx.ocir.io/toddrsharp/greenthumb/greenthumb-client:latest .

    - name: 'Docker Push'
      run: docker push phx.ocir.io/toddrsharp/greenthumb/greenthumb-client:latest
