# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:  
        java-version: '11.0.3'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew assemble
      
    - name: 'Login To OCIR'
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.OCIR_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.OCIR_PASSWORD }}
        DOCKER_REGISTRY_URL: phx.ocir.io
      
    - name: 'Docker Build'
      run: docker build -t phx.ocir.io/toddrsharp/greenthumb/greenthumb-client:latest .

    - name: 'Docker Push'
      uses: actions-hub/docker@master
      with:
        args: push phx.ocir.io/toddrsharp/greenthumb/greenthumb-client:latest

    - name: 'Deploy Container'
      uses: appleboy/ssh-action@master
      with:
        host: greenthumb.toddrsharp.com
        username: opc
        key: ${{ secrets.VM_PRIV_KEY }}
        script: |
          echo ${{ secrets.OCIR_PASSWORD }} |  | docker login --username ${{ secrets.OCIR_USERNAME }} --password-stdin
          docker stop project-greenthumb
          docker pull phx.ocir.io/toddrsharp/greenthumb/greenthumb-client:latest
          docker run -d --name project-greenthumb --restart=always --env MICRONAUT_ENVIRONMENTS=oraclecloud --env MQTT_CLIENT_USER_NAME=${{ secrets.MQTT_CLIENT_USER_NAME }} --env DATASOURCES_DEFAULT_USERNAME=${{ secrets.DATASOURCES_DEFAULT_USERNAME }} --env MQTT_CLIENT_PASSWORD=${{ secrets.MQTT_CLIENT_PASSWORD }} --env DATASOURCES_DEFAULT_OCID=${{ secrets.DATASOURCES_DEFAULT_OCID }} --env MQTT_CLIENT_CLIENT_ID=${{ secrets.MQTT_CLIENT_CLIENT_ID }} --env DATASOURCES_DEFAULT_PASSWORD=${{ secrets.DATASOURCES_DEFAULT_PASSWORD }} --env MQTT_CLIENT_SERVER_URI=${{ secrets.MQTT_CLIENT_SERVER_URI }} --env DATASOURCES_DEFAULT_WALLET_PASSWORD=${{ secrets.DATASOURCES_DEFAULT_WALLET_PASSWORD }} -p 8080:8080 -p 80:80 phx.ocir.io/toddrsharp/greenthumb/greenthumb-client:latest
